/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Network */
        get: operations["get_network_api_v1_config_network_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Feedback */
        post: operations["add_feedback_api_v1_findings__finding_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/findings/{finding_id}/slice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Slice */
        post: operations["create_slice_api_v1_findings__finding_id__slice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence */
        get: operations["get_evidence_api_v1_incidents__incident_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Narrative */
        get: operations["get_narrative_api_v1_incidents__incident_id__narrative_get"];
        put?: never;
        /** Start Narrative */
        post: operations["start_narrative_api_v1_incidents__incident_id__narrative_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_incidents__incident_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_api_v1_investigations_get"];
        put?: never;
        /** Create Investigation */
        post: operations["create_investigation_api_v1_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_api_v1_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        /** Remove Investigation */
        delete: operations["remove_investigation_api_v1_investigations__investigation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Anomalies */
        get: operations["list_anomalies_api_v1_investigations__investigation_id__anomalies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/investigations/{investigation_id}/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_investigations__investigation_id__incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slices/{slice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Slice */
        get: operations["get_slice_api_v1_slices__slice_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/slices/{slice_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Slice */
        get: operations["download_slice_api_v1_slices__slice_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomaliesOut */
        AnomaliesOut: {
            /** Promoted Findings */
            promoted_findings: components["schemas"]["FindingOut"][];
            /** Scored Windows */
            scored_windows: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** EvidenceOut */
        EvidenceOut: {
            /** Fields */
            fields: {
                [key: string]: unknown;
            };
            /** Finding Id */
            finding_id: number;
            /** Kind */
            kind: string;
            /** Local Id */
            local_id: string;
            /** Ts */
            ts: string | null;
            /** Zeek Uid */
            zeek_uid: string | null;
        };
        /** EvidencePage */
        EvidencePage: {
            /** Items */
            items: components["schemas"]["EvidenceOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** FeedbackIn */
        FeedbackIn: {
            /**
             * Label
             * @enum {string}
             */
            label: "true_positive" | "false_positive" | "expected_benign";
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** FeedbackOut */
        FeedbackOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finding Id */
            finding_id: number;
            /** Id */
            id: number;
            /**
             * Label
             * @enum {string}
             */
            label: "true_positive" | "false_positive" | "expected_benign";
            /** Note */
            note: string;
        };
        /** FindingOut */
        FindingOut: {
            /** Benign Causes */
            benign_causes: unknown[];
            /** Confidence */
            confidence: string;
            /** Detector Id */
            detector_id: string;
            /** Detector Version */
            detector_version: string;
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /** Evidence Total */
            evidence_total: number;
            /** Feedback */
            feedback: components["schemas"]["FeedbackOut"][];
            /** Id */
            id: number;
            /** Local Id */
            local_id: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Primary Entity */
            primary_entity: string;
            /** Secondary Entities */
            secondary_entities: unknown[];
            /** Severity Score */
            severity_score: number;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /** Techniques */
            techniques: components["schemas"]["TechniqueOut"][];
            /** Thresholds */
            thresholds: {
                [key: string]: unknown;
            };
            /** Type */
            type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Db
             * @constant
             */
            db: "ok";
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Worker
             * @enum {string}
             */
            worker: "alive" | "unknown";
        };
        /** IncidentDetailOut */
        IncidentDetailOut: {
            /** Cards */
            cards: {
                [key: string]: unknown;
            }[];
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /** Finding Count */
            finding_count: number;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            /** Id */
            id: number;
            /** Links */
            links: components["schemas"]["LinkOut"][];
            /** Local Id */
            local_id: string;
            /** Playbooks */
            playbooks: string[];
            /** Primary Entity */
            primary_entity: string;
            /** Rank */
            rank: number;
            /** Severity Label */
            severity_label: string;
            /** Severity Score */
            severity_score: number;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /** Summary */
            summary: string;
            /** Types */
            types: string[];
        };
        /** IncidentSummary */
        IncidentSummary: {
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /** Finding Count */
            finding_count: number;
            /** Id */
            id: number;
            /** Links */
            links: components["schemas"]["LinkOut"][];
            /** Local Id */
            local_id: string;
            /** Primary Entity */
            primary_entity: string;
            /** Rank */
            rank: number;
            /** Severity Label */
            severity_label: string;
            /** Severity Score */
            severity_score: number;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /** Types */
            types: string[];
        };
        /** Inference */
        Inference: {
            /** Alternative Explanations */
            alternative_explanations: string[];
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Knowledge Ids */
            knowledge_ids?: string[];
            /** Statement */
            statement: string;
            /** Supporting Ids */
            supporting_ids: string[];
        };
        /** InvestigationDetail */
        InvestigationDetail: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: string;
            /** Incident Count */
            incident_count: number;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            } | null;
            /** Original Name */
            original_name: string;
            /** Profile */
            profile: {
                [key: string]: unknown;
            } | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Stage */
            stage: string;
            /** Stage Ms */
            stage_ms: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Warnings */
            warnings: unknown[] | null;
        };
        /** InvestigationSummary */
        InvestigationSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: string;
            /** Incident Count */
            incident_count: number;
            /** Original Name */
            original_name: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /** Stage */
            stage: string;
            /** Status */
            status: string;
        };
        /** LinkOut */
        LinkOut: {
            /** From Incident */
            from_incident: number;
            /** From Local */
            from_local: string;
            /** Reason */
            reason: string;
            /** To Incident */
            to_incident: number;
            /** To Local */
            to_local: string;
            /** Type */
            type: string;
        };
        /**
         * NarrativeOut
         * @description Optional machine-generated narrative. `output` is present ONLY when it passed validation;
         *     otherwise the template summary of the incident is what to show.
         */
        NarrativeOut: {
            /** Created At */
            created_at: string | null;
            /** Entities */
            entities: {
                [key: string]: string;
            };
            /** Label */
            label: string;
            /** Model */
            model: string;
            output: components["schemas"]["NarrativeOutput"] | null;
            /** Prompt Hash */
            prompt_hash: string;
            /** Provider */
            provider: string;
            /** Reasons */
            reasons: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "not_requested" | "pending" | "validated" | "rejected" | "unavailable";
        };
        /** NarrativeOutput */
        NarrativeOutput: {
            /** Inferences */
            inferences: components["schemas"]["Inference"][];
            /** Observed */
            observed: components["schemas"]["Observed"][];
            /** Open Questions */
            open_questions: string[];
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /** Summary */
            summary: string;
        };
        /** NetworkOut */
        NetworkOut: {
            /** Allowlist */
            allowlist: {
                [key: string]: unknown;
            };
            /** Internal Cidrs */
            internal_cidrs: string[];
            /** Known Hosts */
            known_hosts: {
                [key: string]: string[];
            };
        };
        /** Observed */
        Observed: {
            /** Evidence Ids */
            evidence_ids: string[];
            /** Statement */
            statement: string;
        };
        /** Recommendation */
        Recommendation: {
            /** Action */
            action: string;
            /** Rationale Ids */
            rationale_ids: string[];
        };
        /** SliceAccepted */
        SliceAccepted: {
            /** Slice Id */
            slice_id: number;
            /** Status */
            status: string;
        };
        /** SliceOut */
        SliceOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finding Id */
            finding_id: number;
            /** Id */
            id: number;
            /** Packets */
            packets: number | null;
            /** Size Bytes */
            size_bytes: number | null;
            /** Status */
            status: string;
        };
        /** TechniqueOut */
        TechniqueOut: {
            /** Phrase */
            phrase: string;
            /** Technique Id */
            technique_id: string;
        };
        /** UploadAccepted */
        UploadAccepted: {
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_network_api_v1_config_network_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_feedback_api_v1_findings__finding_id__feedback_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                finding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_slice_api_v1_findings__finding_id__slice_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                finding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SliceAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_incident_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_v1_incidents__incident_id__evidence_get: {
        parameters: {
            query?: {
                finding_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_narrative_api_v1_incidents__incident_id__narrative_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_narrative_api_v1_incidents__incident_id__narrative_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_incidents__incident_id__report_get: {
        parameters: {
            query?: {
                format?: "md" | "html";
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                incident_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_api_v1_investigations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_api_v1_investigations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_api_v1_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_investigation_api_v1_investigations__investigation_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_anomalies_api_v1_investigations__investigation_id__anomalies_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnomaliesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_investigations__investigation_id__incidents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slice_api_v1_slices__slice_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                slice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SliceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_slice_api_v1_slices__slice_id__download_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                slice_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
